create table clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    nome varchar2(50) not null,
    idade number(3) check (idade between 0 and 130),
    email varchar2(100) not null
);

alter table clientes add  idade number(3) check (idade between 0 and 130);


select * from clientes;